name: CI Pipeline

on:
  push:
    branches:
      - main
    
  pull_request:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Build Docker image for testing
      run: docker build -f Dockerfile.dev -t drapp-test .

    - name: Run tests in Docker container
      run: docker run --name drapp-test-container drapp-test npm run test

    - name: Exit
      run: docker rm -f drapp-test-container
