name: CI Pipeline

on:
  push:
    branches:
      - main
    
  pull_request:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image for testing
      run: docker build -f Dockerfile.dev -t drapp-test .

    - name: Run tests in Docker container
      run: docker run --name drapp-test-container drapp-test npm run test

    - name: Set up GCP SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to App Engine
      run: gcloud app deploy --quiet